### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by daliansky** [daggeryu/DELL-inspiron-5488#1]
蓝牙睡眠唤醒失效建议在10.14.x下面将三个驱动安装进/L/E/重建缓存

**Comment by daggeryu** [comment]
我买了两张卡，一张DW1560，一张BCM94360cs2，之前使用DW1560不存在睡眠唤醒蓝牙失效的问题。只有bcm94360cs2出现此问题。参考你的SSDT-7560-DW1560.aml好像解决了此问题。昨天到今天没出现。

**Comment by Harry-Borrsion** [comment]
所以用这个网卡的话，要购买转接卡和网卡对嘛

**Comment by youwei997** [comment]
我的蓝牙为啥用不了

**Comment by Harry-Borrsion** [comment]
你有更换论坛里用的那个网卡吗？没有的话是驱动不了蓝牙的

**Comment by daggeryu** [comment]
建议你们都更换网卡。dw1560，或者原装卡，自带的英特尔网卡没必要去折腾。

**Comment by kyojjj** [comment]
大佬，我更换了dw1560的网卡，黑苹果下驱动正常，但是win10下一直搜不到5G信号，你有这个问题吗？
