### ISSUE TITLE
我觉得10.15可以搞一波

### ISSUE THREAD

**Issue by mlpzaq9998** [daggeryu/DELL-inspiron-5488#10]
经测试问题不大
触摸板设置不能识别但正常使用
wifi 显示第三方 dw1820a
电池显示错误 
其他应该没啥问题

**Comment by daggeryu** [comment]
我的都高了，电池驱动换回ACPIBatteryManager.kext电池就显示了，触摸板也可以设置了。网卡我不存在问题，免驱卡。

**Comment by mlpzaq9998** [comment]
我升级安装 除了wifi显示第三方 长时间睡眠重启 没别的问题 试试你的

**Comment by mlpzaq9998** [comment]
CodecCommander.kext 这个驱动我发现我电脑加上hdmi盒盖开机音频还是笔记本，去掉后一切正常

**Comment by mlpzaq9998** [comment]
更新了驱动貌似什么都正常了 长时间睡眠还没测试
https://github.com/mlpzaq9998/DELL-inspiron-5488

**Comment by mlpzaq9998** [comment]
10.15 facetime打开不黑屏了 刚发现 你的能激活码

**Comment by mlpzaq9998** [comment]
再次更新驱动所有都完美了 就是登陆iculd 垃圾桶会出现莫名其妙的垃圾 FaceTime激活不了

**Comment by mlpzaq9998** [comment]
Cpu变频那俩驱动不要貌似变频也没问题

**Comment by daggeryu** [comment]
CodecCommander.kext是修复睡眠唤醒问题的，cpufriend可以不要，我的做了低频，我发现有些基友不要也有800MHz，我的没有，所以弄了下。15facetime的确没问题了。

**Comment by mlpzaq9998** [comment]
谢了 明白了 还有那俩触摸板驱动补丁有啥用？貌似移除了也没影响

**Comment by UloveMheart** [comment]
从14升级到15后无法进入系统了。。（显示In Memory Panic Stackshot Succeeded ** Bytes Traced 287136 **)
用提供的15efi文件替换没办法找到macOS启动项
