### ISSUE TITLE
请问redmibook 配置和这个一模一样的，可以使用这个efi吗？

### ISSUE THREAD

**Issue by samwang0041** [daggeryu/DELL-inspiron-5488#14]

**Comment by daggeryu** [comment]
你可以试试，你说的一样，估计只是处理器一样。

**Comment by zelozzz** [comment]
bios可能不一样

**Comment by zelozzz** [comment]
bois 可能不一样，建议不要容易搞坏机器，可以搜下你的机型应该是有相同的




------------------ 原始邮件 ------------------
发件人: "daggeryu"<notifications@github.com>; 
发送时间: 2019年9月22日(星期天) 中午12:27
收件人: "daggeryu/DELL-inspiron-5488"<DELL-inspiron-5488@noreply.github.com>; 
抄送: "1172435011"<1172435011@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [daggeryu/DELL-inspiron-5488] 请问redmibook 配置和这个一模一样的，可以使用这个efi吗？ (#14)




Closed #14.
 
&mdash;
