### ISSUE TITLE
求助，更新到15后出现内存恐慌

### ISSUE THREAD

**Issue by Alex-dengxz** [daggeryu/DELL-inspiron-5488#18]
从14升级到15后无法进入系统了。。（用原efi显示In Memory Panic Stackshot Succeeded ** Bytes Traced 287136 **)
用提供的15efi文件替换没办法找到macOS启动项

**Comment by zhihuangdaren** [comment]
试试这个？https://github.com/daggeryu/DELL-inspiron-5488/blob/master/卡DVMT解决办法.md

**Comment by Alex-dengxz** [comment]
按照这个试过了，依然是一样的结果

**Comment by Alex-dengxz** [comment]
在把lilu.kext更新到1.3.7解决了，但是触控板失灵
