### ISSUE TITLE
求助主题不生效，耳机有电流声

### ISSUE THREAD

**Issue by ghost** [daggeryu/DELL-inspiron-5488#19]
<dict>
			<key>Entries</key>
			<true/>
			<key>Legacy</key>
			<false/>
			<key>Linux</key>
			<false/>
			<key>Tool</key>
			<false/>
		</dict>
		<key>Theme</key>
		<string>blackMojave</string>
	</dict>

**Comment by daggeryu** [comment]
耳机问题可以试试刚刚更新的ID100

**Comment by ghost** [comment]
更新之后播放设备直接没了

**Comment by ghost** [comment]
Warning: /AppleInternal/Library/Extensions: No such file or directory
rebuilding //System/Library/PrelinkedKernels/prelinkedkernel
KernelCache ID: 7CCF954C270A5C18AD53CB8488F34BC8
symlink("../../../PrelinkedKernels/prelinkedkernel", "/System/Library/Caches/com.apple.kext.caches/Startup/kernelcache") failed 2 (No such file or directory)
kextcache updated critical boot files, requesting launchd reboot

**Comment by daggeryu** [comment]
两个id都没声音吗
