### ISSUE TITLE
唤醒死机

### ISSUE THREAD

**Issue by mlpzaq9998** [daggeryu/DELL-inspiron-5488#2]
大佬5488 用你的最新efi 短时间唤醒唤醒正常 3分钟以上睡眠唤醒屏幕不亮，键盘灯亮，外接hdmi不显示应该是死机，怎么解决啊

**Comment by youwei997** [comment]
希望作者会修复吧。百度了也不知道这么搞，升级10.14.5后就变成这样了

**Comment by youwei997** [comment]
看了作者的更新日志，关闭bios里面一个选项，但是win下指纹就不能用了

**Comment by mlpzaq9998** [comment]
换了别人的config唤醒不死机

**Comment by daggeryu** [comment]
我目前使用没有你们说的这个问题呢，你们都是5488什么版本的。我在以前10.14.4遇到过睡眠唤醒屏幕不亮的问题，重新用hackintool打补丁就好了，虽然有点玄学，你们可以试试。

**Comment by mlpzaq9998** [comment]
感谢大佬解答，新手小白，可以告诉hackintool打哪个布丁吗？

**Comment by mlpzaq9998** [comment]
我的5488 i5 8250u 显卡MX250 显示器LGD05

**Comment by mlpzaq9998** [comment]
https://github.com/MartinYik/Dell-Inspiron-5580-hackintosh
我用他的config不死机 大佬可以看看什么原因吗

**Comment by mlpzaq9998** [comment]
系统10.14.5

**Comment by youwei997** [comment]
不过我设置了不休眠了，还能接受。就是我clover进win10一直没声音要反复安装驱动，而且还不一定有效果，这是为啥。一进win10声音就显示❌。。

**Comment by daggeryu** [comment]
我看了那个5580的efi，几乎完全一样的。等会儿我重新上传完整的efi，你们试试吧。

**Comment by mlpzaq9998** [comment]
好的

**Comment by daggeryu** [comment]
clover进入win10没有声音的请删除EFI/clover/driver65uefi下的“AudioDxe-64.efi”这个文件就好了。

**Comment by daggeryu** [comment]
我重新上传了，你试试看，如果还是不行你可以直接用5580的那个config，应该没有功能缺失，

**Comment by youwei997** [comment]
好的，感谢大神

**Comment by mlpzaq9998** [comment]
大佬你上传的BOOTX64.efi有问题进不去引导 我替换了就可以了 fn+insert睡眠无效 
4:换上bcm94360cs2后蓝牙概率睡眠唤醒掉驱动（dw1560没有此问题），增加ssdt修复。这个可能需要根据自己的实际情况作修改。无此问题可以选择删除。
是删除 SSDT-UIAC.aml里这个嘛
    External (_SB_.PCI0.XHC_.RHUB.HS06, DeviceObj)

    Method (\_SB.PCI0.XHC.RHUB.HS06._DSM, 4, NotSerialized)  // _DSM: Device-Specific Method
    {
        If ((Arg2 == Zero))
        {
            Return (Buffer (One)
            {
                 0x03                                             // .
            })
        }

        Return (Package (0x0E)
        {
            "vendor-id", 
            Buffer (0x04)
            {
                 0xAC, 0x05, 0x00, 0x00                           // ....
            }, 

            "device-id", 
            Buffer (0x04)
            {
                 0xBF, 0x82, 0x00, 0x00                           // ....
            }, 

            "subsystem-vendor-id", 
            Buffer (0x04)
            {
                 0x6B, 0x10, 0x00, 0x00                           // k...
            }, 

            "subsystem-id", 
            Buffer (0x04)
            {
                 0x17, 0x01, 0x00, 0x00                           // ....
            }, 

            "compatible", 
            "pci14e4,43a0", 
            "IOName", 
            "pci14e4,43a0", 
            "name", 
            "pci14e4,43a0"
        })
    }

**Comment by daggeryu** [comment]
谢谢提醒，我重新弄一下，改为单个hotpatch。

**Comment by daggeryu** [comment]
你再试试，你没换网卡就删除SSDT-5488-cs2.aml这个文件。

**Comment by mlpzaq9998** [comment]
好的我试试

**Comment by daggeryu** [comment]
我刚刚失误了，忘了编译，你注意更新时间，我现在在睡眠，我试试睡眠5分钟，能唤醒不。

**Comment by daggeryu** [comment]
睡眠6分钟唤醒也没问题，你们测试了说一下看看。

**Comment by mlpzaq9998** [comment]
好的 我测试测试 BOOT/BOOTX64.efi有问题进不去引导 需要更新 替换以前的可以

**Comment by daggeryu** [comment]
好了，更新了。睡眠还有问题吗。

**Comment by mlpzaq9998** [comment]
试试 20分钟 他那个睡眠一夜没问题 测试好回复

**Comment by daggeryu** [comment]
我的睡眠一页也没问题的，我一般不关机的。

**Comment by mlpzaq9998** [comment]
好用 睡眠没问题 对了大佬 你的14寸 1080p 是用什么方法解决显示字小的？调分辨率太模糊 hidpi 用了开机会一直有大苹果 用的那个一键开启

**Comment by daggeryu** [comment]
我有更新了，刚刚忘了加驱动x86的文件，技能显示有问题。我直接用的1600X900这个分辨率，咩开hidpi。

**Comment by mlpzaq9998** [comment]
用的这个
https://github.com/xzhih/one-key-hidpi/blob/master/README-zh.md
1600*900太模糊了

**Comment by mlpzaq9998** [comment]
有办法只开启1600*900 hidpi吗

**Comment by daggeryu** [comment]
不影响啊，就用它的，但是有机友反应唤醒四分之一屏幕，用hackintool开启hidpi不会，我觉得看着还好，一直没开。

**Comment by mlpzaq9998** [comment]
大佬还有个问题 最新版用了U盘不显示外置磁盘，我的DW1820 不能用 AirportBrcmFixup 驱动了 ，显示未安装硬件

**Comment by mlpzaq9998** [comment]
蓝牙VirtualSMC 添加id能显示

**Comment by daggeryu** [comment]
我用的引导跟你一样啊u盘能显示外置磁盘，你能否上图，1820a太逊色了，没做研究你自己研究一下吧。

**Comment by mlpzaq9998** [comment]
我拍个照片 U盘直接在访达里 不在桌面有黄图标了
![IMG_0047](https://user-images.githubusercontent.com/6046642/57995418-83999480-7af4-11e9-9489-fea54cc02c00.JPG)

**Comment by daggeryu** [comment]
你再换我现在的引导试试，刚刚更新了SSDT-UIAC.aml，还不行你就删除它使用hackintool重新定制usb。

**Comment by mlpzaq9998** [comment]
你之前的是可以的 我试试

**Comment by daggeryu** [comment]
我看你的出现了指纹，我的定制吧指纹去了的

**Comment by mlpzaq9998** [comment]
这是用的你编译那个x86那个版本的 我下载最新的试试

**Comment by mlpzaq9998** [comment]
不行还是有指纹 usb显示内置硬盘样式

**Comment by daggeryu** [comment]
又更新了，这次应该ok了。

**Comment by mlpzaq9998** [comment]
谢谢 大佬 我试试

**Comment by mlpzaq9998** [comment]
嗯 这次好了 指纹也没了 大佬 DW1820 之前可以用AirportBrcmFixup 驱动 用最新的驱动不了 应该从哪里入手？

**Comment by youwei997** [comment]
大佬们，你们的5488会降频吗，我这个频率非常不稳定，一直降频。见鬼了

**Comment by mlpzaq9998** [comment]
找到网卡问题了 macos 启动时候没加载驱动导致网卡不识别 win下也不识别 win下安装驱动蓝屏 放电后重启 AirportBrcmFixup 就能驱动
