### ISSUE TITLE
5580 更新最新的 efi  进不去系统了 

### ISSUE THREAD

**Issue by lsdo** [daggeryu/DELL-inspiron-5488#28]
please go to https://panic.apple.com to report this panic

好像是 5488.kext 的问题吧。
最后，根据原先的 efi 找回 被5488 替换的驱动，重新装系统。
奇怪的问题
mac store  无线网不好用，链接手机热点好用

**Comment by daggeryu** [comment]
麻烦你再试一次，把错误图片传上来，我这边使用没问题

**Comment by daggeryu** [comment]
dvmt记得改为64mb

**Comment by lsdo** [comment]
抱歉了，，我重新弄了一次efi ，没有这个问题了。应该是我的原因，抱歉，

目前 这个笔记本，使用1560 没出现 蓝牙毛病，这个 efi 很完美

**Comment by lsdo** [comment]
不知道为啥，最新的，触摸板是不好用的 替换原来的驱动就好用了

**Comment by lsdo** [comment]
以后升级，换驱动，遇到问题，拍照给你

**Comment by daggeryu** [comment]
现在的引导触摸板不好用？

**Comment by lsdo** [comment]
是啊。确实不好用，原先的驱动好用

**Comment by daggeryu** [comment]
我的用着没任何毛病啊

**Comment by lsdo** [comment]
应该是我的问题，麻烦您了

**Comment by lsdo** [comment]
这个版本，和以前的版本，就这几天的时间 品了品，，
以前的efi  笔记本 安装dw1560    时不时的蓝牙不好用，
现在的efi  就目前没有这个问题了。，非常感谢
