### ISSUE TITLE
10.15在root账户下,安装ALCPlugFix,耳机还是无声

### ISSUE THREAD

**Issue by GGGGBOMB** [daggeryu/DELL-inspiron-5488#30]
而且 每次都伴随这一个问题 就是装完这个会无限重启.只得重新安装系统
还有就是在10.14还是10.15鬼使神差的发现,蓝牙可以用,不知道怎么回事,因为重新装了一遍,能用的情况也消失了,不知道是个什么原理.用的是inter 9560ac。
望大神解惑

**Comment by daggeryu** [comment]
需要解锁sle权限,自带的网卡不是9560ac,英特尔的网卡蓝牙基本都能用,但是不能关闭,有问题可以来qq群里讨论,现在群里有二十多名机友了

**Comment by GGGGBOMB** [comment]
群号多少呀～
