### ISSUE TITLE
Line-in not detected on Inspiron 5480

### ISSUE THREAD

**Issue by heylucc** [daggeryu/DELL-inspiron-5488#36]
Hello, no matter what I do, I can't get external mic (on a headset) working. It works fine on Windows and Linux, but macOS only shows me the option to use the internal microphone. I believe  that perhaps the pins and nodes are a little bit different between versions and the layout-id 54 doesn't wok for the 5480.

I would be glad to provide a codec dump from Linux if you feel inclined to maybe support it. If not, it's fine and I appreciate the work that has been done to provide a almost-fully-functional layout for AppleALC. Thank you

**Comment by marcos-alexandre82** [comment]
@heylucc 
You can try the one suggested in this video, although it didn't work correctly for me, other people were successful:
https://www.youtube.com/watch?v=q4xZsLyqynE

Don't forget to give feedback, whether or not it worked for you.

;)

**Comment by daggeryu** [comment]
[归档.zip](https://github.com/daggeryu/DELL-Inspiron_5488_5480_5580_5482_5582_Hackintosh/files/4726933/default.zip)
Use it, it is ok, use method please Google

**Comment by heylucc** [comment]
> [归档.zip](https://github.com/daggeryu/DELL-Inspiron_5488_5480_5580_5482_5582_Hackintosh/files/4726933/default.zip)
> Use it, it is ok, use method please Google

Thank you for answering and giving me the suggestion. Unfortunately, it doesn't fix the problem. I had already tried that, but it seems this fix was made specifically for the XPS 9560, which uses another codec.

The pop-up window is shown, but lien-in still doesn't work. It isn't detected by macOS System, as you can see below:

<img width="784" alt="Screen Shot 2020-06-04 at 18 16 20" src="https://user-images.githubusercontent.com/63983390/83811225-c7275800-a68f-11ea-8396-5973f793a425.png">

**Comment by daggeryu** [comment]
[AppleALC.kext.zip](https://github.com/daggeryu/DELL-Inspiron_5488_5480_5580_5482_5582_Hackintosh/files/4733537/AppleALC.kext.zip)
You need to replace him. I passed the test of 10.14.6, and the headset microphone can be used.

**Comment by heylucc** [comment]
> [AppleALC.kext.zip](https://github.com/daggeryu/DELL-Inspiron_5488_5480_5580_5482_5582_Hackintosh/files/4733537/AppleALC.kext.zip)
> You need to replace him. I passed the test of 10.14.6, and the headset microphone can be used.

Thank you! That worked!

Can you tell me what's different between this AppleALC and the official one? so I can try to apply the same changes to future versions if something breaks

**Comment by daggeryu** [comment]
Check his node information, submit it to https://github.com/daggeryu/AppleALC, and it can be used all the time.

**Comment by heylucc** [comment]
> Check his node information, submit it to https://github.com/daggeryu/AppleALC, and it can be used all the time.

Can you tell me where is the file from, exactly? Who created this particular AppleALC mod?
