### ISSUE TITLE
Put up Wi-Fi and bluetooth without replacing the network card

### ISSUE THREAD

**Issue by NexiusTailer** [daggeryu/DELL-inspiron-5488#39]
I think this should work for all of the listed models for which this build is intended, so I will be glad to see this issue pinned.

First of all, let's make bluetooth working. Download this archive ([link](https://github.com/OpenIntelWireless/IntelBluetoothFirmware/releases)) with 2 kexts which should be located in your kext folder with all other ones. And that's it for bluetooth, check if it works in your system settings on macOS, tested on Dell Inspiron 14 5482.

Next, set up the Wi-Fi itself: download "AirportItlwm" ~AND~ OR "itlwm" from here ([link](https://github.com/OpenIntelWireless/itlwm/releases)). Take from the release marked "Latest release" (taking pre-release is not recommended unless you really need some features from it like compatibility with older macOS versions). Put one of these 2 kexts to your kext folder again and boot your macOS system.

Now you're only need an .app file which will finally add your active Wi-Fi icon. Here is it: [link](https://github.com/OpenIntelWireless/HeliPort/releases). Again, it's better to get the stable version by downloading "HeliPort.dmg" from the release labeled "Latest release". Move this app to applications folder and open it. For my part, I can suggest adding it to launch at startup, so as not to enable it manually every time the system starts. Finally, you get a working Wi-Fi with the ability to connect to any wireless networks. Tested also on Dell Inspiron 14 5482.

**Comment by noahsmaximum** [comment]
AirportItlwm should not be used at the same time as itlwm. Not only did the system not load for me (itlwm kept looping while scanning), the guide from the source of those kexts explicitly states not to use them at the same time. Just 
using iltwm and HeliPort works fine afaik.

**Comment by NexiusTailer** [comment]
Thanks for the clarification. Now I'm really curious why the wifi didn't work for me when initially I used only one of the two kexts...

**Comment by noahsmaximum** [comment]
No problem, just keeping an eye out! I do appreciate you finding this
extension. It really makes this inspiron series an even better hackintosh
than the rest!
