### ISSUE TITLE
读卡器是免驱的 可以取消屏蔽 

### ISSUE THREAD

**Issue by mlpzaq9998** [daggeryu/DELL-inspiron-5488#4]
读卡器是免驱的 可以取消屏蔽
 NoTouchID.kext 还是需要的 输密码不卡
hidpi 开1440x810 清晰又不卡 
建议完善

**Comment by daggeryu** [comment]
我没有屏蔽读卡器啊，还有你哪里看出读卡器驱动了呢，usb里没有看到读卡器，我屏蔽的是指纹。hidpi有需要的人会开的，现在就一串代码的事。后期加一个就好。

**Comment by mlpzaq9998** [comment]
但是我插上卡不是别啊 我看了下定制 也是没有屏蔽 我重新定制能用

**Comment by mlpzaq9998** [comment]
![image](https://user-images.githubusercontent.com/6046642/58335663-a4efdd00-7e74-11e9-9cf9-da1c65a6fba1.png)

**Comment by mlpzaq9998** [comment]
这个是我插的内存卡

**Comment by daggeryu** [comment]
我或许应该知道了，麻烦你截一张hackintool下usb的图给我，我有空更新一下，因为我没有读卡器，所以没有测试过，所以定制的usb驱动里就去掉了读卡器那个usb。

**Comment by mlpzaq9998** [comment]
![image](https://user-images.githubusercontent.com/6046642/58336057-89390680-7e75-11e9-9cda-ef688a0a0f75.png)

**Comment by daggeryu** [comment]
ok，我知道了，空了会更新。

**Comment by mlpzaq9998** [comment]
好的 感谢完善
