### ISSUE TITLE
睡眠之后重启

### ISSUE THREAD

**Issue by 131mm** [daggeryu/DELL-inspiron-5488#8]
于5.28日使用您的efi安装成功，各方面满意。但是目前在我的设备上存在一个问题。

设备信息：5488核显版，macOS安装至加装的Intel545s 256G硬盘，网卡还未更换。

问题描述：在自动睡眠、盒盖睡眠、fn+insert睡眠下均存在睡眠5分钟后唤醒时重启问题，复现率100%。

ps：感觉耗电有点快，比deepin还快，还在观察中

**Comment by daggeryu** [comment]
你看看你的bios版本好多少。老得版本睡眠唤醒回重启。我用的2.2.2

**Comment by 0xTract0r** [comment]
你好，你装的是哪个版本的系统？我装10.13的耗电一分钟就掉1%，10.14能好一些，但也是2小时不到就没了。

**Comment by 131mm** [comment]
经过观察，bios1.4.0，新安装完系统后睡眠会重启，安装项目里 的声卡修复会解决睡眠重启问题，挺奇怪。
目前一切正常，顺便也把bios升级到最新。
耗电量依然较大，如图：
![屏幕快照 2019-06-02 下午8.53.23.png](https://i.loli.net/2019/06/02/5cf3c6d061f0139603.png)

**Comment by daggeryu** [comment]
都给你说了更新bios啊，老版本有这个问题，睡眠唤醒概率重启。

**Comment by daggeryu** [comment]
怎么省电别问我，我没做研究。

**Comment by 131mm** [comment]
十分感谢您的贡献
